# Generated by Django 4.2.2 on 2023-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('fathersLastName', models.CharField(max_length=20)),
                ('mothersLastName', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('schedule', models.CharField(blank=True, choices=[('MATUTINO', 'matutino'), ('VESPERTINO', 'vespertino')], null=True)),
                ('typeUser', models.CharField(default='CLIENTE', max_length=10)),
                ('branch', models.CharField(blank=True, choices=[('INSURGENTES', 'insurgentes'), ('CUATRO CAMINOS', 'cuatro caminos'), ('LOMAS ESTRELLA', 'lomas estrella'), ('SANTA FE', 'santa fe'), ('UNIVERSIDAD', 'universidad')], null=True)),
                ('attempt', models.IntegerField(default=0)),
                ('made_by', models.CharField(blank=True, max_length=20, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_delete', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
