# Generated by Django 4.2.2 on 2023-06-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='name',
            field=models.CharField(choices=[('INSURGENTES', 'insurgentes'), ('CUATRO CAMINOS', 'cuatro caminos'), ('LOMAS ESTRELLA', 'lomas estrella'), ('SANTA FE', 'santa fe'), ('UNIVERSIDAD', 'universidad')], unique=True),
        ),
    ]
