# Generated by Django 4.2.2 on 2023-06-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=2)),
                ('release_year', models.IntegerField()),
                ('movies_available', models.IntegerField()),
                ('languages', models.CharField(max_length=15)),
                ('duration', models.CharField(max_length=15)),
                ('cinema_studio', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
