# Generated by Django 4.2.2 on 2023-06-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='classification',
            field=models.CharField(max_length=10),
        ),
    ]
