# Generated by Django 4.2.2 on 2023-06-17 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv', models.CharField(max_length=3)),
                ('cardHolderName', models.CharField(max_length=15)),
                ('fathersLastName', models.CharField(max_length=20)),
                ('mothersLastName', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('status_delete', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
